# Generated by Django 4.1 on 2023-09-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Molo',
        ),
    ]
